### PR TITLE
Add a function for resizing a Window

### PR DESCRIPTION
**Pull request by vainiovano**
It is possible to resize the terminal but it is boring without being able to manually resize a window.

### CODE REVIEW

**Comment by jeff-hughes** [comment]
Hi, is there any update about this PR? I am using pancurses to develop an app with two windows that should each take up half the screen. Right now there is currently no way to resize the windows to maintain them at half the screen when the terminal is resized. Implementing wresize() would be extremely helpful here, instead of having to copy them into new windows and delete the originals.

**Comment by vainiovano** [comment]
The development speed of this library seems to be quite slow. I haven't used pancurses for a long time.

**Comment by cbiffle** [comment]
@vainiovano can you suggest an alternative? Cursive seems like overkill for what I'm doing...

**Comment by jeff-hughes** [comment]
@cbiffle I don't know whether @vainiovano found another solution, but the one I used in the end was to literally just destroy the window and recreate it every time it's resized (see [here](https://github.com/jeff-hughes/shellcaster/blob/master/src/ui/panel.rs#L223)). It's not an elegant solution, but it works and surprisingly doesn't lead to any noticeable slowdown. I just look for the `Input::KeyResize` input and then recreate the window with the new size.

But it would still definitely be nice to have the `wresize()` function implemented.

**Comment by vainiovano** [comment]
Cursive seems to only use one window. Its `KeyResize` handling for pancurses is [here](https://github.com/gyscos/cursive/blob/47d8d231982ad3aad5e5d6873766bbaaa16d2b28/cursive/src/backends/curses/pan.rs#L276-L285). If you need multiple windows, you can recreate them on resize like @jeff-hughes said.

**Comment by ihalila** [comment]
Thanks for the PR!

**Pull request merged**
